version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./fastapi_app/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: ./celery_workers/Dockerfile
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3.12-management"
    volumes:
      - ./rabbitmq_definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management.load_definitions "/etc/rabbitmq/definitions.json"
    ports:
      - "15672:15672"
      - "5672:5672"

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=pyamqp://sdgp_admin:<password>@rabbitmq:15672/

    command: celery flower
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
