version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/fastapi/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: ./docker/celery/Dockerfile
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq:5672/
    command: celery flower
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
