FROM rabbitmq:3.12-management

# Copy the custom RabbitMQ configuration file into the container
COPY ./rabbitmq/rabbitmq.conf /etc/rabbitmq/rabbitmq.conf

# Copy the custom definitions file into the container
COPY ./rabbitmq/definitions.json /etc/rabbitmq/definitions.json


