name: Build docker images and push to backend-quizzifyme.venura.dev
permissions:
  id-token: write
  contents: read
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: microservice

      - name: Create .env file
        run: |
          echo SUPABASE_URL=${{ secrets.SUPABASE_URL }} >> ./celery_workers/.env
          echo SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} >> ./celery_workers/.env
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> ./celery_workers/.env
          echo SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }} >> ./celery_workers/.env
          echo PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }} >> ./celery_workers/.env
          echo PINECONE_INDEX_NAME=${{ secrets.PINECONE_INDEX_NAME }} >> ./celery_workers/.env
          echo RUNPOD_WORKER_ID=${{ secrets.RUNPOD_WORKER_ID }} >> ./celery_workers/.env
          echo RUNPOD_API_KEY=${{ secrets.RUNPOD_API_KEY }} >> ./celery_workers/.env
          echo RUNPOD_API_SECRET=${{ secrets.RUNPOD_API_KEY }} >> ./celery_workers/.env
          echo GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} >> ./celery_workers/.env
          echo BROKER_URL=${{ secrets.BROKER_URL }} >> ./celery_workers/.env
          echo BACKEND_URL=${{ secrets.BACKEND_URL }} >> ./celery_app/.env

      - name: Download gte/small
        run: |
          apt-get update && apt-get install -y git-lfs
          git lfs install
          git clone https://huggingface.co/thenlper/gte-small ./celery_workers/src/api/gte-small

      - name: Login to private image registry
        run: docker login -u ${{ secrets.IMAGE_REGISTRY_USERNAME }} -p ${{ secrets.IMAGE_REGISTRY_PASSWORD }} backend-quizzifyme.venura.dev

      - name: Build, tag, and push celery worker docker image to private registry
        run: |
          docker build -t backend-quizzifyme.venura.dev/sdgp-backend-worker:latest  -f ./celery_workers/Dockerfile  .
          docker push backend-quizzifyme.venura.dev/sdgp-backend-worker:latest

      - name: Build, tag, and push fastapi docker image to private registry
        run: |
          docker build -t backend-quizzifyme.venura.dev/sdgp-backend-web:latest  -f ./fastapi_app/Dockerfile  .
          docker push backend-quizzifyme.venura.dev/sdgp-backend-web:latest
