name: Unit testing using Pytest
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Create .env file
        run: |
          echo SUPABASE_URL=${{ secrets.SUPABASE_URL }} >> ./celery_workers/.env
          echo SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} >> ./celery_workers/.env
          echo TEST_USERNAME=${{ secrets.TEST_USERNAME }} >> ./celery_workers/.env
          echo TEST_PASSWORD=${{ secrets.TEST_PASSWORD }} >> ./celery_workers/.env
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r celery_workers/requirements.txt 
          pip install -r fastapi_app/requirements.txt 
          pip install pytest
      - name: Download gte/small
        run: |
          apt-get update && apt-get install -y git-lfs
          git lfs install
          git clone https://huggingface.co/thenlper/gte-small ./celery_workers/src/api/gte-small
      - name: Run pytest
        run: |
          pytest
