name: Docker Compose

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  # schedule:
  #   - cron: '16 10 * * *'
  workflow_dispatch:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables from secrets
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY: ${{secrets.PINECONE_API_KEY }}
          PINECONE_INDEX_NAME: ${{secrets.PINECONE_INDEX_NAME }}
          HUGGINGFACE_SECRET: ${{secrets.HUGGINGFACE_SECRET }}
          HUGGINGFACE_ENDPOINT_URL: ${{secrets.HUGGINGFACE_ENDPOINT_URL }}
        run: |
          echo "SUPABASE_URL=${SUPABASE_URL}" >> .env
          echo "SUPABASE_KEY=${SUPABASE_KEY}" >> .env
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> .env
          echo "PINECONE_API_KEY=${PINECONE_API_KEY}" >> .env
          echo "PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME}" >> .env
          echo "HUGGINGFACE_SECRET=${HUGGINGFACE_SECRET}" >> .env
          echo "HUGGINGFACE_ENDPOINT_URL=${HUGGINGFACE_ENDPOINT_URL}" >> .env
          


      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@6e04d228eb30da1757ee4e1dd75a0ec73a653e06 #v3.1.1
        with:
          cosign-release: 'v2.1.1'
          
      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Docker compose 
      - name: Docker Compose Action
        uses: isbang/compose-action@v1.5.1
